### ISSUE TITLE
项目启动时报错，quart 相关的表不存在。

### ISSUE THREAD

**Issue by ycg000344** [jeeagile/jeeagile#1]
按照在线文档将几个SQL文件导入了DB中，在项目启动时报错，报错信息为 quart 框架的表不存在。
发现在 `agile_quartz.properties`文件中的属性配置：
```
org.quartz.jobStore.tablePrefix=agile_quartz_
```
注释后可以正常启动，给大佬反馈下，可能在线文档中有这个地方的说明，但是我没找到。

感谢大佬的开源。

**Comment by jeeagile** [comment]
agile_quartz.properties的配置文件里设置了自定义表前缀，最新代码已注释掉，谢谢建议
